### ISSUE TITLE
Port Bindings and host mode

### ISSUE THREAD

**Issue by adamphetamine** [bsherman/netmaker-traefik#1]
Hi, 
I wanted to flag the following- especially in case I've done something wrong-

If you run up the supplied docker-compose.yml you'll get an error and Traefik will be unable to start
`'docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings'`

Removing the port bindings in the .yml file seems to fix this-

```
    ports:
      - "80:80"
      - "443:443"
```

Please let me know if this is incorrect!

**Comment by adamphetamine** [comment]
I've just done this setup again and did not have this issue...So I must have been wrong!

**Comment by mfuezesi** [comment]
I've got the same problem. How have you solved this?

**Comment by bsherman** [comment]
My apologies, I have no idea how I managed to overlook these comments for so long.

Yes, that config was probably bad on my part.   

As of the update which I just pushed for version 0.11, I'm no longer using host mode networking, since it's not required by the default netmaker configuration. So this problem should be resolved for future attempts.
