### ISSUE TITLE
Add link to offical netmaker with traefik example

### ISSUE THREAD

**Issue by callumgare** [bsherman/netmaker-traefik#6]
Can a link to the official netmaker docker compose example with traefik be included in the header in the "The official netmaker docker-compose example now uses Traefik, so I'm archiving this repo" header?

It's not obvious where to find it and the Readme of the offical repo still links very prominently to this repo. I believe this might be the what is considered the official example? https://docs.netmaker.org/server-installation.html#compose-file-annotated

**Comment by bsherman** [comment]
Yep, I'll do that. Thanks for the suggestion!

I do intend to get this back into a current state as a "traefik way" to run netmaker, I had archived it because for a while netmaker itself was going to use traefik, but now they don't, so I want to pick it up again. Regardless, your suggestion is helpful.

**Comment by bsherman** [comment]
README is updated, thank you again!

**Comment by callumgare** [comment]
Great! Glad to hear it, thanks 😊
